import argparse

def get_args_parser(subparsers):
    subparsers.add_argument('--batch-size', default=24, type=int, help='Batch size per device')
    subparsers.add_argument('--epochs', default=5, type=int)

    # Model parameters
    subparsers.add_argument('--model', default='vit_base_patch16_224', type=str, metavar='MODEL', help='Name of model to train')
    subparsers.add_argument('--original_model', default='vit_base_patch16_224', type=str, metavar='ORIGINAL MODEL', help='Name of model to inference task id')
    subparsers.add_argument('--input-size', default=224, type=int, help='images input size')
    subparsers.add_argument('--pretrained', default=True, help='Load pretrained model or not')
    subparsers.add_argument('--drop', type=float, default=0.0, metavar='PCT', help='Dropout rate (default: 0.)')
    subparsers.add_argument('--drop-path', type=float, default=0.0, metavar='PCT', help='Drop path rate (default: 0.)')

    # Optimizer parameters
    subparsers.add_argument('--opt', default='adam', type=str, metavar='OPTIMIZER', help='Optimizer (default: "adam"')
    subparsers.add_argument('--opt-eps', default=1e-8, type=float, metavar='EPSILON', help='Optimizer Epsilon (default: 1e-8)')
    subparsers.add_argument('--opt-betas', default=(0.9, 0.999), type=float, nargs='+', metavar='BETA', help='Optimizer Betas (default: (0.9, 0.999), use opt default)')
    subparsers.add_argument('--clip-grad', type=float, default=2.0, metavar='NORM',  help='Clip gradient norm (default: None, no clipping)')
    subparsers.add_argument('--momentum', type=float, default=0.9, metavar='M', help='SGD momentum (default: 0.9)')
    subparsers.add_argument('--weight-decay', type=float, default=0.0, help='weight decay (default: 0.0)')
    subparsers.add_argument('--reinit_optimizer', type=bool, default=True, help='reinit optimizer (default: True)')

    # Learning rate schedule parameters
    subparsers.add_argument('--sched', default='constant', type=str, metavar='SCHEDULER', help='LR scheduler (default: "constant"')
    subparsers.add_argument('--lr', type=float, default=0.03, metavar='LR', help='learning rate (default: 0.03)')
    subparsers.add_argument('--init_lr', type=float, default=0.03, metavar='INITLR', help='init learning rate (default: 0.03)')
    subparsers.add_argument('--lr-noise', type=float, nargs='+', default=None, metavar='pct, pct', help='learning rate noise on/off epoch percentages')
    subparsers.add_argument('--lr-noise-pct', type=float, default=0.67, metavar='PERCENT', help='learning rate noise limit percent (default: 0.67)')
    subparsers.add_argument('--lr-noise-std', type=float, default=1.0, metavar='STDDEV', help='learning rate noise std-dev (default: 1.0)')
    subparsers.add_argument('--warmup-lr', type=float, default=1e-6, metavar='LR', help='warmup learning rate (default: 1e-6)')
    subparsers.add_argument('--min-lr', type=float, default=1e-5, metavar='LR', help='lower lr bound for cyclic schedulers that hit 0 (1e-5)')
    subparsers.add_argument('--decay-epochs', type=float, default=30, metavar='N', help='epoch interval to decay LR')
    subparsers.add_argument('--warmup-epochs', type=int, default=5, metavar='N', help='epochs to warmup LR, if scheduler supports')
    subparsers.add_argument('--cooldown-epochs', type=int, default=10, metavar='N', help='epochs to cooldown LR at min_lr, after cyclic schedule ends')
    subparsers.add_argument('--patience-epochs', type=int, default=10, metavar='N', help='patience epochs for Plateau LR scheduler (default: 10')
    subparsers.add_argument('--decay-rate', '--dr', type=float, default=0.1, metavar='RATE', help='LR decay rate (default: 0.1)')
    subparsers.add_argument('--unscale_lr', type=bool, default=True, help='scaling lr by batch size (default: True)')
    subparsers.add_argument('--milestones', default=[15], type=int)
    subparsers.add_argument('--weight_decay', default=5e-4, type=float)

    # Augmentation parameters
    subparsers.add_argument('--color-jitter', type=float, default=None, metavar='PCT', help='Color jitter factor (default: 0.3)')
    subparsers.add_argument('--aa', type=str, default=None, metavar='NAME',
                        help='Use AutoAugment policy. "v0" or "original". " + \
                             "(default: rand-m9-mstd0.5-inc1)'),
    subparsers.add_argument('--smoothing', type=float, default=0.1, help='Label smoothing (default: 0.1)')
    subparsers.add_argument('--train-interpolation', type=str, default='bicubic',
                        help='Training interpolation (random, bilinear, bicubic default: "bicubic")')

    # * Random Erase params
    subparsers.add_argument('--reprob', type=float, default=0.0, metavar='PCT', help='Random erase prob (default: 0.25)')
    subparsers.add_argument('--remode', type=str, default='pixel', help='Random erase mode (default: "pixel")')
    subparsers.add_argument('--recount', type=int, default=1, help='Random erase count (default: 1)')

    # Data parameters
    subparsers.add_argument('--data-path', default='/local_datasets/', type=str, help='dataset path')
    subparsers.add_argument('--dataset', default='Split-IMAGENET-R', type=str, help='dataset name')
    subparsers.add_argument('--shuffle', default=False, help='shuffle the data order')
    subparsers.add_argument('--output_dir', default='./output', help='path where to save, empty for no saving')
    subparsers.add_argument('--device', default='cuda', help='device to use for training / testing')
    subparsers.add_argument('--seed', default=42, type=int)
    subparsers.add_argument('--eval', action='store_true', help='Perform evaluation only')
    subparsers.add_argument('--num_workers', default=4, type=int)
    subparsers.add_argument('--pin-mem', action='store_true',
                        help='Pin CPU memory in DataLoader for more efficient (sometimes) transfer to GPU.')
    subparsers.add_argument('--no-pin-mem', action='store_false', dest='pin_mem',
                        help='')
    subparsers.set_defaults(pin_mem=True)

    # distributed training parameters
    subparsers.add_argument('--world_size', default=4, type=int,
                        help='number of distributed processes')
    subparsers.add_argument('--dist_url', default='env://', help='url used to set up distributed training')

    # Continual learning parameters
    subparsers.add_argument('--num_tasks', default=10, type=int, help='number of sequential tasks')
    subparsers.add_argument('--max_train_tasks', default=0, type=int, help='stop after this many tasks while preserving the num_tasks dataset partition; 0 runs all tasks')
    subparsers.add_argument('--train_mask', default=True, type=bool, help='if using the class mask at training')
    subparsers.add_argument('--task_inc', default=False, type=bool, help='if doing task incremental')

    # lora parameters
    subparsers.add_argument('--lora_type', default='continual', choices=['continual', 'hide'],type=str, help='lora type')
    subparsers.add_argument('--lora_pool', action="store_true")
    subparsers.add_argument('--size', default=10, type=int,)
    subparsers.add_argument('--lora_rank', default=4, type=int,)
    subparsers.add_argument('--lora_momentum', default=0.1, type=float,)

    subparsers.add_argument('--con', default=0.1, type=float,)
    subparsers.add_argument('--ctird_task_selection', default='legacy', choices=['legacy', 'task_energy'], type=str, help='select CTIRD source adapters using legacy bottom classes or top task energy')
    subparsers.add_argument('--ctird_task_temperature', default=0.1, type=float)
    subparsers.add_argument('--ctird_task_weighting', default='uniform', choices=['uniform', 'energy'], type=str, help='weight selected CTIRD source ranks uniformly or by task energy')
    subparsers.add_argument('--ctird_weight_temperature', default=1.0, type=float)
    subparsers.add_argument('--ctird_weight_floor', default=0.2, type=float)
    subparsers.add_argument('--ctird_online_aligned', action='store_true', help='compute CTIRD teachers online on the exact current batch instead of using batch-indexed cached relations')
    subparsers.add_argument('--ctird_online_temperature', default=1.0, type=float, help='temperature for aggregating TII class logits into old-task probability mass')
    subparsers.add_argument('--ctird_online_ranks_per_batch', default=1, type=int, help='number of cyclic top-K old-task ranks evaluated per online CTIRD batch')
    subparsers.add_argument('--ctird_online_reduction', default='sum', choices=['sum', 'mean'], type=str, help='preserve the paper K-loss sum or keep total online CTIRD strength constant as K grows')
    subparsers.add_argument('--ctird_semantic_selection', action='store_true', help='use semantics only to disambiguate uncertain online CTIRD teacher selection')
    subparsers.add_argument('--ctird_semantic_weight', default=0.1, type=float, help='maximum semantic mixture weight for uncertain CTIRD teacher selection')
    subparsers.add_argument('--ctird_semantic_temperature', default=0.1, type=float, help='temperature for semantic old-task scores')
    subparsers.add_argument('--ctird_semantic_margin', default=0.15, type=float, help='TII top-two probability margin below which semantic selection is activated')
    subparsers.add_argument('--K', default=5, type=int,)
    subparsers.add_argument('--En', default='gen', choices=['msp', 'gen'])
    subparsers.add_argument('--tau', default=-10, type=float)
    subparsers.add_argument('--task_routing_mode', default='class', choices=['class', 'task_energy'], type=str, help='route evaluation samples by top class or aggregated task energy')
    subparsers.add_argument('--task_routing_temperature', default=0.1, type=float)

    # ViT parameters
    subparsers.add_argument('--global_pool', default='token', choices=['token', 'avg'], type=str, help='type of global pooling for final sequence')
    subparsers.add_argument('--head_type', default='token', choices=['token', 'gap', 'prompt', 'token+prompt'], type=str, help='input type of classification head')
    subparsers.add_argument('--freeze', default=['blocks', 'patch_embed', 'cls_token', 'norm', 'pos_embed'], nargs='*', type=list, help='freeze part in backbone model')

    subparsers.add_argument('--crct_epochs', default=30, type=int)
    subparsers.add_argument('--crct_use_all_samples', action='store_true', help='use every balanced synthetic replay sample during classifier correction')
    subparsers.add_argument('--crct_balanced_batches', action='store_true', help='interleave classes so each classifier-correction batch is approximately balanced')
    subparsers.add_argument('--crct_head_only', action='store_true', help='update only the classifier head during CRCT')
    subparsers.add_argument('--crct_old_class_distill', action='store_true')
    subparsers.add_argument('--crct_distill_weight', default=0.25, type=float)
    subparsers.add_argument('--crct_distill_temperature', default=2.0, type=float)
    subparsers.add_argument('--crct_distill_confidence', default=0.6, type=float)
    subparsers.add_argument('--crct_anchor_weight', default=0.0, type=float)
    subparsers.add_argument('--crct_reliability_weighting', action='store_true')
    subparsers.add_argument('--crct_reliability_floor', default=0.25, type=float)
    subparsers.add_argument('--crct_reliability_power', default=1.0, type=float)
    subparsers.add_argument('--crct_reliability_preserve_mass', action='store_true')
    subparsers.add_argument('--crct_reliability_preserve_class_mass', action='store_true')
    subparsers.add_argument('--crct_old_row_lr_scale', default=1.0, type=float)
    subparsers.add_argument('--crct_validation_gate', action='store_true', help='accept only a proxy-validated interpolation of the post-CRCT classifier')
    subparsers.add_argument('--crct_validation_steps', default=10, type=int)
    subparsers.add_argument('--crct_validation_max_alpha', default=1.0, type=float, help='maximum accepted interpolation toward the post-CRCT classifier')
    subparsers.add_argument('--crct_validation_samples_per_component', default=8, type=int)
    subparsers.add_argument('--crct_validation_cov_scale', default=0.25, type=float)
    subparsers.add_argument('--crct_validation_repeats', default=1, type=int)
    subparsers.add_argument('--crct_validation_max_old_acc_drop', default=0.0, type=float, help='maximum per-old-class accuracy drop in percentage points on held-out feature anchors')
    subparsers.add_argument('--crct_validation_min_acc_gain', default=0.0, type=float, help='minimum all-class macro accuracy gain in percentage points')
    subparsers.add_argument('--crct_validation_min_top5_gain', default=0.0, type=float)
    subparsers.add_argument('--crct_validation_min_task_gain', default=0.0, type=float)
    subparsers.add_argument('--crct_validation_min_ce_gain', default=0.0, type=float, help='minimum all-class macro CE reduction')
    subparsers.add_argument('--crct_validation_current_real', action='store_true', help='validate CRCT plasticity on transient features from the current task train set')
    subparsers.add_argument('--crct_validation_current_samples_per_class', default=16, type=int)
    subparsers.add_argument('--crct_validation_max_current_acc_drop', default=0.0, type=float, help='maximum per-current-class accuracy drop in percentage points')
    subparsers.add_argument('--crct_validation_current_ce_tolerance', default=0.0, type=float, help='maximum macro CE increase allowed on transient current-task features')
    subparsers.add_argument('--train_inference_task_only', action='store_true')
    subparsers.add_argument('--original_model_mlp_structure', default=[2], type=int)
    subparsers.add_argument('--ca_lr', default=0.005, type=float)
    subparsers.add_argument('--trained_original_model', default='', type=str)
    subparsers.add_argument('--not_train_ca', action='store_true')
    subparsers.add_argument('--ca_epochs', default=30, type=int)
    subparsers.add_argument('--ca_storage_efficient_method', default='multi-centroid', choices=['covariance', 'multi-centroid', 'variance'], type=str)
    subparsers.add_argument('--n_centroids', default=10, type=int)
    subparsers.add_argument('--cfs_sampling', action='store_true', help='use CFS-selected Gaussian samples for CRCT')
    subparsers.add_argument('--cfs_epochs', default=50, type=int)
    subparsers.add_argument('--cfs_lr', default=0.01, type=float)
    subparsers.add_argument('--cfs_momentum', default=0.9, type=float)
    subparsers.add_argument('--cfs_hidden_dim', default=512, type=int)
    subparsers.add_argument('--cfs_batch_size', default=256, type=int)
    subparsers.add_argument('--cfs_train_max_samples', default=1024, type=int)
    subparsers.add_argument('--cfs_candidate_multiplier', default=3, type=int)
    subparsers.add_argument('--cfs_tau', default=1.0, type=float)
    subparsers.add_argument('--cfs_init_strategy', default='random', choices=['random', 'mean'], type=str, help='initial candidate selection strategy for CFS diversity sampling')
    subparsers.add_argument('--cfs_old_classes_only', action='store_true', help='use CFS replay only for old classes; keep Gaussian replay for classes from the current task')
    subparsers.add_argument('--cfs_boundary_replay', action='store_true', help='mix diverse CFS samples with samples near the current classifier boundary')
    subparsers.add_argument('--cfs_boundary_ratio', default=0.5, type=float)
    subparsers.add_argument('--cfs_boundary_multiplier', default=3, type=int)
    subparsers.add_argument('--cfs_boundary_density_quantile', default=0.9, type=float)
    subparsers.add_argument('--cfs_boundary_target_side', action='store_true', help='prefer in-distribution boundary samples still classified on the target side')
    subparsers.add_argument('--cfs_core_replay_ratio', default=0.0, type=float)
    subparsers.add_argument('--cfs_core_multiplier', default=4, type=int)
    subparsers.add_argument('--cfs_distribution_filter', action='store_true', help='filter CFS Gaussian candidates by class feature distribution before diversity selection')
    subparsers.add_argument('--cfs_filter_multiplier', default=3, type=int)
    subparsers.add_argument('--cfs_filter_cosine_weight', default=0.0, type=float)
    subparsers.add_argument('--cfs_paper_style', action='store_true', help='use paper-style multi-step CFS selection')
    subparsers.add_argument('--cfs_moment_match', action='store_true', help='restore class mean and marginal standard deviation after CFS selection')
    subparsers.add_argument('--cfs_selection_ratio', default=0.5, type=float)
    subparsers.add_argument('--cfs_selection_steps', default=5, type=int)
    subparsers.add_argument('--cfs_step_candidates', default=0, type=int)
    subparsers.add_argument('--cfs_pmi_diagnostic', action='store_true', help='compare Gaussian and CFS targets after partial model inversion without training or changing checkpoints')
    subparsers.add_argument('--cfs_pmi_diag_task', default=1, type=int)
    subparsers.add_argument('--cfs_pmi_diag_classes', default=4, type=int)
    subparsers.add_argument('--cfs_pmi_diag_targets_per_class', default=5, type=int)
    subparsers.add_argument('--cfs_pmi_diag_real_samples_per_class', default=64, type=int)
    subparsers.add_argument('--cfs_pmi_diag_cfs_epochs', default=200, type=int)
    subparsers.add_argument('--cfs_pmi_diag_split_block', default=1, type=int)
    subparsers.add_argument('--cfs_pmi_diag_layer_steps', default=100, type=int)
    subparsers.add_argument('--cfs_pmi_diag_full_steps', default=300, type=int)
    subparsers.add_argument('--cfs_pmi_diag_layer_lr', default=0.05, type=float)
    subparsers.add_argument('--cfs_pmi_diag_full_lr', default=0.01, type=float)
    subparsers.add_argument('--cfs_pmi_diag_class_weight', default=0.1, type=float)
    subparsers.add_argument('--cfs_pmi_diag_moment_weight', default=0.01, type=float)
    subparsers.add_argument('--cfs_task_logit_calibration', action='store_true', help='fit task-wise rematching scale/bias from CFS features generated only from aggregate class statistics')
    subparsers.add_argument('--cfs_logit_calibration_samples_per_class', default=48, type=int)
    subparsers.add_argument('--cfs_logit_calibration_steps', default=200, type=int)
    subparsers.add_argument('--cfs_logit_calibration_lr', default=0.05, type=float)
    subparsers.add_argument('--cfs_logit_calibration_max_scale', default=1.25, type=float)
    subparsers.add_argument('--cfs_logit_calibration_max_bias', default=0.5, type=float)
    subparsers.add_argument('--cfs_logit_calibration_regularization', default=0.05, type=float)
    subparsers.add_argument('--cfs_logit_calibration_old_margin_weight', default=0.5, type=float)
    subparsers.add_argument('--cfs_logit_calibration_old_tolerance', default=0.0, type=float)
    subparsers.add_argument('--cfs_logit_calibration_min_gain', default=0.0, type=float)
    subparsers.add_argument('--cfs_logit_calibration_max_old_class_drop', default=0.0, type=float)
    subparsers.add_argument('--cfs_logit_calibration_batch_size', default=1024, type=int)
    subparsers.add_argument('--strict_exemplar_free', action='store_true', help='reject any configuration that stores per-example real features or rereads historical train images')
    subparsers.add_argument('--replay_anchor_ctird', action='store_true', help='generate cached CFS-PMI pseudo-images and preserve old LoRA relations while training each new LoRA')
    subparsers.add_argument('--replay_anchor_weight', default=0.05, type=float)
    subparsers.add_argument('--replay_anchor_batch_size', default=20, type=int)
    subparsers.add_argument('--replay_anchor_temperature', default=1.0, type=float)
    subparsers.add_argument('--replay_anchor_teacher_confidence', default=0.2, type=float)
    subparsers.add_argument('--replay_anchor_images_per_class', default=5, type=int)
    subparsers.add_argument('--replay_inversion_candidate_multiplier', default=2, type=int)
    subparsers.add_argument('--replay_anchor_cache_dir', default='', type=str)
    subparsers.add_argument('--replay_inversion_split_block', default=5, type=int)
    subparsers.add_argument('--replay_inversion_layer_steps', default=200, type=int)
    subparsers.add_argument('--replay_inversion_full_steps', default=600, type=int)
    subparsers.add_argument('--replay_inversion_layer_lr', default=0.1, type=float)
    subparsers.add_argument('--replay_inversion_full_lr', default=0.01, type=float)
    subparsers.add_argument('--replay_inversion_class_weight', default=0.1, type=float)
    subparsers.add_argument('--replay_inversion_tv_weight', default=0.0005, type=float)
    subparsers.add_argument('--crct_real_feature_replay', action='store_true', help='mix a compact memory of real class features with Gaussian/CFS replay during classifier correction')
    subparsers.add_argument('--crct_real_memory_per_class', default=48, type=int, help='maximum number of representative real features retained per class')
    subparsers.add_argument('--crct_real_replay_ratio', default=0.25, type=float, help='fraction of each class correction budget filled with real feature memory')
    subparsers.add_argument('--crct_real_old_replay_ratio', default=0.35, type=float, help='real-feature fraction for old classes during classifier correction')
    subparsers.add_argument('--crct_real_new_replay_ratio', default=0.10, type=float, help='real-feature fraction for classes in the current task')
    subparsers.add_argument('--crct_real_hard_ratio', default=0.5, type=float, help='fraction of real replay chosen by lowest current target margin')
    subparsers.add_argument('--crct_real_outlier_quantile', default=0.9, type=float, help='exclude the most distant real features before diversity-based memory selection')
    subparsers.add_argument('--crct_real_diversity_weight', default=0.7, type=float, help='tradeoff between feature coverage and proximity to the class center when building memory')
    subparsers.add_argument('--crct_hybrid_samples_per_class', default=0, type=int, help='total real plus synthetic correction samples per class and epoch; 0 uses batch_size * 5')
    subparsers.add_argument('--prototype_rematching', action='store_true', help='rerank candidate task adapters with stored real-feature prototypes at evaluation')
    subparsers.add_argument('--prototype_candidate_tasks', default=2, type=int)
    subparsers.add_argument('--prototype_temperature', default=0.07, type=float)
    subparsers.add_argument('--prototype_classifier_weight', default=0.5, type=float)
    subparsers.add_argument('--prototype_task_prior_weight', default=0.25, type=float)
    subparsers.add_argument('--prototype_task_prior_temperature', default=1.0, type=float)
    subparsers.add_argument('--shared_prototype_router', action='store_true', help='route tasks with prototypes extracted from one frozen TII backbone space')
    subparsers.add_argument('--shared_prototype_temperature', default=0.07, type=float)
    subparsers.add_argument('--shared_prototype_tii_weight', default=0.25, type=float)
    subparsers.add_argument('--shared_prototype_classifier_weight', default=0.5, type=float)
    subparsers.add_argument('--shared_prototype_tii_temperature', default=1.0, type=float)
    subparsers.add_argument('--replay_logit_calibration', action='store_true', help='fit task-wise classifier scale and bias using retained real-feature memory')
    subparsers.add_argument('--replay_calibration_steps', default=200, type=int)
    subparsers.add_argument('--replay_calibration_lr', default=0.05, type=float)
    subparsers.add_argument('--replay_calibration_max_scale', default=1.5, type=float)
    subparsers.add_argument('--replay_calibration_max_bias', default=1.0, type=float)
    subparsers.add_argument('--replay_calibration_regularization', default=0.01, type=float)
    subparsers.add_argument('--replay_calibration_old_margin_weight', default=0.25, type=float)
    subparsers.add_argument('--replay_calibration_old_tolerance', default=0.0, type=float)
    subparsers.add_argument('--replay_calibration_min_gain', default=0.0, type=float)
    subparsers.add_argument('--replay_calibration_samples_per_class', default=48, type=int)
    subparsers.add_argument('--replay_calibration_batch_size', default=1024, type=int)
    subparsers.add_argument('--replay_task_router', action='store_true', help='train a validated nonlinear task router on retained shared-backbone features')
    subparsers.add_argument('--replay_router_epochs', default=50, type=int)
    subparsers.add_argument('--replay_router_lr', default=0.001, type=float)
    subparsers.add_argument('--replay_router_weight_decay', default=0.01, type=float)
    subparsers.add_argument('--replay_router_hidden_dim', default=256, type=int)
    subparsers.add_argument('--replay_router_dropout', default=0.1, type=float)
    subparsers.add_argument('--replay_router_patience', default=8, type=int)
    subparsers.add_argument('--replay_router_validation_ratio', default=0.25, type=float)
    subparsers.add_argument('--replay_router_min_validation_gain', default=0.25, type=float)
    subparsers.add_argument('--replay_router_samples_per_class', default=48, type=int)
    subparsers.add_argument('--replay_router_batch_size', default=256, type=int)
    subparsers.add_argument('--exhaustive_rematching', action='store_true', help='score every seen task with its own LoRA and merge task-local class logits')
    subparsers.add_argument('--vectorized_exhaustive_rematching', action='store_true', help='preserve exhaustive scoring while batching multiple task LoRAs in each model call')
    subparsers.add_argument('--vectorized_exhaustive_task_chunk_size', default=4, type=int)
    subparsers.add_argument('--soft_mixture_rematching', action='store_true', help='mix TII top-k LoRA residuals by normalized task posterior in one forward pass')
    subparsers.add_argument('--soft_mixture_hard_rematching', action='store_true', help='route with a soft LoRA mixture, then classify with the selected hard LoRA')
    subparsers.add_argument('--soft_hard_selector_rematching', action='store_true', help='choose between soft-mixture and routed hard-LoRA logits using a label-free normalized margin')
    subparsers.add_argument('--soft_local_hard_refinement', action='store_true', help='preserve soft cross-task evidence while using hard-LoRA rankings inside the routed task')
    subparsers.add_argument('--soft_mixture_top_k', default=4, type=int)
    subparsers.add_argument('--soft_mixture_task_temperature', default=1.0, type=float)
    subparsers.add_argument('--soft_mixture_logit_temperature', default=1.0, type=float)
    subparsers.add_argument('--soft_mixture_tii_prior_weight', default=0.3, type=float)
    subparsers.add_argument('--exhaustive_tii_prior_weight', default=0.1, type=float)
    subparsers.add_argument('--exhaustive_logit_temperature', default=1.0, type=float)
    subparsers.add_argument('--exhaustive_max_calibration_weight', default=0.0, type=float, help='blend raw cross-task maxima toward unit-standardized maxima while preserving within-task class logit gaps')
    subparsers.add_argument('--exhaustive_tii_class_weight', default=0.0, type=float, help='fuse centered TII class evidence within each task while preserving that task maximum')
    subparsers.add_argument('--exhaustive_tii_class_temperature', default=1.0, type=float)
    subparsers.add_argument('--exhaustive_local_prototype_weight', default=0.0, type=float, help='fuse task-local real-memory prototype evidence while preserving each task maximum')
    subparsers.add_argument('--exhaustive_local_prototype_temperature', default=0.07, type=float)
    subparsers.add_argument('--hierarchical_rematching', action='store_true', help='combine normalized task posterior and task-conditional class probabilities across all seen LoRAs')
    subparsers.add_argument('--hierarchical_tii_weight', default=0.3, type=float)
    subparsers.add_argument('--hierarchical_max_weight', default=1.0, type=float)
    subparsers.add_argument('--hierarchical_margin_weight', default=0.5, type=float)
    subparsers.add_argument('--hierarchical_entropy_weight', default=0.5, type=float)
    subparsers.add_argument('--hierarchical_class_temperature', default=1.0, type=float)
    subparsers.add_argument('--hierarchical_task_temperature', default=1.0, type=float)
    subparsers.add_argument('--budgeted_rematching', action='store_true', help='preserve original rematching and use exhaustive fallback only for a fixed budget of risky samples')
    subparsers.add_argument('--budgeted_fallback_fraction', default=0.2, type=float)
    subparsers.add_argument('--budgeted_tii_prior_weight', default=0.3, type=float)
    subparsers.add_argument('--budgeted_logit_temperature', default=1.0, type=float)
    subparsers.add_argument('--budgeted_disagreement_weight', default=2.0, type=float)
    subparsers.add_argument('--budgeted_classifier_weight', default=0.5, type=float)
    subparsers.add_argument('--progressive_oracle_audit', action='store_true', help='run exhaustive once and audit the theoretical 2-to-4-to-all cascade')
    subparsers.add_argument('--stage_drift_audit', action='store_true', help='decompose old-task decay into true-adapter local drift and cross-task score competition using exhaustive logits already computed by the oracle audit')
    subparsers.add_argument('--progressive_arrow_audit', action='store_true', help='audit layerwise Arrow-style LoRA parameter routing and its fixed union with TII candidates')
    subparsers.add_argument('--progressive_lora_response_audit', action='store_true', help='audit normalized full-rank K/V LoRA response routing and its fixed union with TII candidates')
    subparsers.add_argument('--progressive_prediction_proposal_audit', action='store_true', help='audit tasks proposed by top class predictions from the initial hard LoRAs')
    subparsers.add_argument('--progressive_prediction_closure_audit', action='store_true', help='audit threshold-free expansion until evaluated LoRAs propose no unseen task')
    subparsers.add_argument('--progressive_prediction_closure_tii_tail_audit', action='store_true', help='evaluate closure top-1 with zero-LoRA TII probability completion for excluded task tails')
    subparsers.add_argument('--progressive_prediction_beam_closure_audit', action='store_true', help='audit leader-closed beam-2 prediction expansion with TII tail completion')
    subparsers.add_argument('--progressive_prediction_budget_closure_audit', action='store_true', help='audit all-frontier prediction closure under a fixed five-adapter cap with TII tail completion')
    subparsers.add_argument('--progressive_prediction_majority_closure_audit', action='store_true', help='audit TII-majority top-one anchoring with cap-five closure for ambiguous samples')
    subparsers.add_argument('--progressive_prediction_consensus_closure_audit', action='store_true', help='audit top-two raw adapter consensus anchoring with cap-five closure fallback')
    subparsers.add_argument('--progressive_prediction_self_owner_audit', action='store_true', help='route within the consensus-cap5 evaluated set using self-endorsing adapters, task-vote support, and TII-rank tie breaking')
    subparsers.add_argument('--progressive_prediction_corroborated_owner_audit', action='store_true', help='rescue consensus only when a disagreeing self-owner receives at least two votes from evaluated adapters')
    subparsers.add_argument('--progressive_prediction_owner_mass_audit', action='store_true', help='rescue uncertified consensus routes using each evaluated adapter owner-task probability mass')
    subparsers.add_argument('--progressive_prediction_owner_consensus_hedge_audit', action='store_true', help='average owner-mass and consensus probabilities with equal prior on rerouted ambiguous samples')
    subparsers.add_argument('--report_conventional_cost', action='store_true', help='log per-sample LoRA and forward-call cost of the default HRM-PET (DRM+CRM) evaluation path')
    subparsers.add_argument('--router_recall_audit', action='store_true', help='measure how highly alternative TII task-score aggregations (max/energy/margin/mean) rank the exhaustive winner, to quantify free strict routing headroom')
    subparsers.add_argument('--rp_head', action='store_true', help='routing-free RanPAC-style classifier: frozen random projection + nonlinearity, then ridge on the accumulated Gram matrix and class prototypes; bypasses the task-inference bottleneck entirely')
    subparsers.add_argument('--rp_dim', default=5000, type=int, help='random projection width M (RanPAC default 10000; 5000 halves the Gram cost)')
    subparsers.add_argument('--rp_activation', default='relu', choices=['relu', 'square', 'gelu', 'none'], type=str)
    subparsers.add_argument('--rp_lambda', default=10000.0, type=float, help='ridge regularizer added to the Gram diagonal before inversion')
    subparsers.add_argument('--rp_lambda_criterion', default='mse', type=str, choices=['mse', 'cosine', 'accuracy'], help="what the lambda sweep optimises; 'mse' is RanPAC's held-out squared error, 'cosine' is the scale-invariant Frobenius cosine between predictions and targets, which does not reward the magnitude shrinkage that large lambda buys and that the per-sample standardisation in the blend discards anyway; 'accuracy' scores held-out top-1 directly, which needs the current task's held-out features in memory but measures the quantity that is actually wanted -- on ImageNet-R the head's own accuracy peaks a decade below where squared error puts it")
    subparsers.add_argument('--rp_bare_model', default='', type=str, help="checkpoint name for the --rp_bare_extractor snapshot only; empty means use --original_model. Set it to vit_base_patch16_224_augreg_in1k to test whether the published no-first-session ImageNet-R numbers were measured on an ImageNet-1k fine-tuned backbone -- ImageNet-R is 200 ImageNet-1k classes redrawn, so that choice would lift ImageNet-R and leave CUB alone")
    subparsers.add_argument('--rp_lambda_scope', default='task', type=str, choices=['task', 'pooled'], help="which data the lambda sweep ranges over; 'task' rebuilds the 80:20 split from scratch every task, which is RanPAC's own procedure, while 'pooled' lets it accumulate across every task seen so far. Pooling biases the choice upward: the norm of the Gram matrix grows linearly with sample count and the best ridge grows with that norm, so ten tasks pooled favour a larger lambda than one task alone. 'pooled' reproduces the earlier ImageNet-R measurement that selected 1e5 at every task")
    subparsers.add_argument('--rp_lambda_search', action='store_true', help="choose lambda per task the way RanPAC does, by splitting the current task 80:20 and sweeping 17 orders of magnitude against held-out squared error, instead of using the fixed --rp_lambda; old tasks are never touched and no features are stored, since the validation error is closed-form in the second-order statistics already kept")
    subparsers.add_argument('--rp_seed', default=1993, type=int, help='seed for the frozen random projection (regenerated, never stored)')
    subparsers.add_argument('--rp_calibrate', action='store_true', help='fit one scalar temperature on training scores so the head Loss is comparable to a softmax classifier (only the scalar is kept)')
    subparsers.add_argument('--rp_normalize', default='none', choices=['none', 'l2', 'scale'], type=str, help='feature scaling before the random projection; raw ViT pre_logits scale distorts the ReLU projection and the single ridge lambda')
    subparsers.add_argument('--rp_feature_source', default='original', choices=['original', 'lora'], type=str, help='original = frozen TII backbone features (no routing at all); lora = one fixed HRM-PET adapter used as first-session adaptation, still routing-free')
    subparsers.add_argument('--rp_lora_task', default=0, type=int, help='which task adapter provides the fixed feature space when rp_feature_source=lora (0 = first session, RanPAC-style); it must not vary per task or the Gram matrix mixes incompatible spaces')
    subparsers.add_argument('--rp_logit_blend', default=0.0, type=float, help='weight on the HRM-PET classifier log-probabilities blended into the head scores; free because it comes from the same adapter forward (0 = pure head)')
    subparsers.add_argument('--rp_pin_extractor', action='store_true', help='freeze the task-1 TII snapshot as the RP feature extractor; without it the per-task checkpoint reload mixes incompatible feature spaces in the Gram matrix')
    subparsers.add_argument('--rp_bare_extractor', action='store_true', help="pin a freshly created PRETRAINED backbone as the RP extractor instead of the TII snapshot; original_model is not the raw ViT (its weights come from the TII checkpoint), so this is the only way to measure the no-first-session-adaptation condition")
    subparsers.add_argument('--rp_input_norm', default='none', choices=['none', 'half', 'cifar_half'], type=str, help="input range for the RP head's frozen extractor: 'half' maps ToTensor()'s [0,1] to the [-1,1] the ImageNet-21K ViT checkpoint was trained on; the LoRA path is left untouched")
    subparsers.add_argument('--rp_route_audit', action='store_true', help='measure whether RP-head routing and TII routing fail on the same samples; the union bounds what fusing the two routers could recover')
    subparsers.add_argument('--classifier_union_audit', action='store_true', help='measure whether the RP head, treated as a classifier, is correct where the routed HRM-PET head is wrong; bounds what a classifier-level fusion could add on top of the routing gain')
    subparsers.add_argument('--layer_stat_router', action='store_true', help='third routing signal from per-task transformer-block activation statistics (PMI-CFS layer-wise prior), scored by diagonal-Gaussian KL; needs no extra adapter call')
    subparsers.add_argument('--rp_route_fusion', action='store_true', help='route by fusing RP-head and TII task scores, then classify with the routed task LoRA; the two routers fail on different samples so their union exceeds HRM-PET routing on every dataset measured')
    subparsers.add_argument('--rp_route_fusion_weight', default=0.5, type=float, help='weight on TII in the fused task log-probabilities (0 = RP head only, 1 = TII only)')
    subparsers.add_argument('--rp_route_fusion_ls_weight', default=0.0, type=float, help='weight on the layer-statistics router added to the fused task scores; keep small since that router is weak alone but complementary')
    subparsers.add_argument('--rp_class_fusion_weight', default=0.0, type=float, help='weight on the RP head as a second classifier, blended with the routed HRM-PET head after DRM/CRM (0 = routed head only); both are standardized over valid classes first')
    subparsers.add_argument('--rp_class_fusion_sharpen', default=1.0, type=float, help='scale the fused class scores before the loss; blending flattens the winner margin and cross-entropy penalises that, and scaling is monotone so accuracy is unchanged')
    subparsers.add_argument('--rp_fusion_ramp', default=0.0, type=float, help='ramp both fusions with the number of tasks seen, as (seen/total)**ramp; 0 keeps the weight constant, and the ramp reaches 1.0 at the final stage so the reported final row is unchanged either way')
    subparsers.add_argument('--rp_fusion_ramp_scope', default='both', type=str, choices=['both', 'class', 'route'], help='which fusion the ramp applies to; the RP head is a weak classifier early but a strong router from the first stage, so ramping the route weight costs routing accuracy for nothing')
    subparsers.add_argument('--rp_class_fusion_gate', default='none', type=str, choices=['none', 'margin', 'margin_both', 'entropy'], help="scale the class-fusion weight per sample by how undecided the routed head is; 'margin' uses its normalised top-2 margin, 'margin_both' additionally scales by the RP head's own margin so the blend opens only when the routed head is undecided AND the RP head is decided, 'entropy' uses normalised entropy, 'none' fuses every sample equally")
    subparsers.add_argument('--rp_class_fusion_min_tasks', default=1, type=int, help='only blend the RP head once this many tasks have been seen; its Gram estimate is unreliable with few classes and the blend costs accuracy in the first stages')
    subparsers.add_argument('--rp_route_fusion_drm', action='store_true', help='hand the fused route to the existing DRM/CRM refinement instead of replacing it; keeps the stage that carries the baseline and improves only the routing that precedes it')
    subparsers.add_argument('--gaussian_rescoring', action='store_true', help='class-incremental prediction by per-class Gaussian (Mahalanobis) fit over stored cls_mean/cls_cov instead of energy-based re-matching; wrong-task features are OOD for a task Gaussians so hijacks are suppressed')
    subparsers.add_argument('--gaussian_cov_mode', default='diagonal', choices=['full', 'diagonal', 'tied'], type=str, help='covariance model for Gaussian re-scoring: full per-class, diagonal per-class, or tied (shared mean covariance across seen classes)')
    subparsers.add_argument('--gaussian_shrinkage', default=0.1, type=float, help='shrink each covariance toward its mean-diagonal by this fraction before inversion (robustness with few samples per class)')
    subparsers.add_argument('--gaussian_include_logdet', action='store_true', help='add the -0.5*logdet(cov) normalizer to the Gaussian score (proper log-likelihood); off = pure Mahalanobis distance')
    subparsers.add_argument('--gaussian_score_weight', default=1.0, type=float, help='weight on the Gaussian log-score in the final per-class score')
    subparsers.add_argument('--gaussian_logit_weight', default=0.0, type=float, help='weight on the per-task LoRA classifier logit blended into the final per-class score (0 = pure Gaussian)')
    subparsers.add_argument('--gaussian_logit_temperature', default=1.0, type=float, help='temperature applied to the LoRA classifier logit before blending into the Gaussian score')
    subparsers.add_argument('--prediction_closure_rematching', action='store_true', help='run operational adaptive prediction closure with top-1-safe TII tail completion')
    subparsers.add_argument('--prediction_proposal_rematching', action='store_true', help='run only TII initial LoRAs plus fixed-budget tasks proposed by their class predictions')
    subparsers.add_argument('--prediction_proposal_initial_branch_audit', action='store_true', help='audit free per-sample complementarity between proposal output and the already-computed initial TII-top1 adapter output')
    subparsers.add_argument('--prediction_proposal_cross_adapter_audit', action='store_true', help='audit full-class consensus and oracle headroom across the already-evaluated proposal adapters')
    subparsers.add_argument('--prediction_proposal_tii_completion', action='store_true', help='reserve TII probability mass for classes whose task LoRA was not evaluated while preserving routed top-1')
    subparsers.add_argument('--prediction_proposal_task_mass_fusion', action='store_true', help='combine TII task posterior with per-LoRA conditional class probabilities without calibration data')
    subparsers.add_argument('--prediction_proposal_conditional_fusion', action='store_true', help='normalize logits within each candidate task before applying the fixed standardized TII prior')
    subparsers.add_argument('--prediction_proposal_crm_confidence_fusion', action='store_true', help='fuse task-conditional LoRA probabilities using HRM generalized-entropy confidence and the fixed TII prior')
    subparsers.add_argument('--prediction_proposal_crm_confidence_temperature', default=0.1, type=float)
    subparsers.add_argument('--prediction_proposal_initial_count', default=2, type=int)
    subparsers.add_argument('--prediction_proposal_count', default=2, type=int)
    subparsers.add_argument('--prediction_proposal_top_classes', default=5, type=int)
    subparsers.add_argument('--prediction_proposal_iterative', action='store_true', help='propose later task candidates from all LoRAs evaluated in earlier fixed-budget waves')
    subparsers.add_argument('--prediction_proposal_first_wave_count', default=2, type=int)
    subparsers.add_argument('--calibrated_progressive_rematching', action='store_true', help='train conservative 2-to-4-to-all halting gates on train images before evaluation')
    subparsers.add_argument('--progressive_gate_samples_per_class', default=12, type=int)
    subparsers.add_argument('--progressive_gate_validation_ratio', default=0.25, type=float)
    subparsers.add_argument('--progressive_gate_hidden_dim', default=64, type=int)
    subparsers.add_argument('--progressive_gate_dropout', default=0.1, type=float)
    subparsers.add_argument('--progressive_gate_lr', default=0.001, type=float)
    subparsers.add_argument('--progressive_gate_weight_decay', default=0.01, type=float)
    subparsers.add_argument('--progressive_gate_batch_size', default=256, type=int)
    subparsers.add_argument('--progressive_gate_epochs', default=60, type=int)
    subparsers.add_argument('--progressive_gate_patience', default=10, type=int)
    subparsers.add_argument('--progressive_gate_target_precision', default=0.995, type=float)
    subparsers.add_argument('--progressive_gate_min_coverage', default=0.02, type=float)
    subparsers.add_argument('--progressive_gate_loss_tolerance', default=0.05, type=float)
    subparsers.add_argument('--progressive_gate_stage2_min_samples_per_class', default=4, type=int)
    subparsers.add_argument('--progressive_gate_stage2_context_ratio', default=0.25, type=float)
    subparsers.add_argument('--progressive_gate_stage2_target_precision', default=1.0, type=float)
    subparsers.add_argument('--progressive_gate_stage2_loss_tolerance', default=0.0, type=float)
    subparsers.add_argument('--progressive_output_temperature_scaling', action='store_true')
    subparsers.add_argument('--progressive_output_temperature_ratio', default=0.25, type=float)
    subparsers.add_argument('--progressive_output_temperature_min', default=0.5, type=float)
    subparsers.add_argument('--progressive_output_temperature_max', default=4.0, type=float)
    subparsers.add_argument('--progressive_output_temperature_steps', default=129, type=int)
    subparsers.add_argument('--progressive_uncertainty_smoothing', action='store_true')
    subparsers.add_argument('--progressive_smoothing_strength', default=0.5, type=float)
    subparsers.add_argument('--progressive_smoothing_max', default=0.05, type=float)
    subparsers.add_argument('--progressive_lora_batch_ranks', default=1, type=int, help='evaluate this many adjacent TII-ranked LoRAs in one GPU forward without crossing a halting boundary')
    subparsers.add_argument('--progressive_rematching', action='store_true', help='evaluate LoRAs in TII-ranked stages and expand uncertain samples to exhaustive')
    subparsers.add_argument('--progressive_initial_candidates', default=2, type=int)
    subparsers.add_argument('--progressive_intermediate_candidates', default=4, type=int)
    subparsers.add_argument('--progressive_tii_prior_weight', default=0.3, type=float)
    subparsers.add_argument('--progressive_logit_temperature', default=1.0, type=float)
    subparsers.add_argument('--progressive_stage1_tii_margin', default=1.0, type=float)
    subparsers.add_argument('--progressive_stage1_adapter_margin', default=0.75, type=float)
    subparsers.add_argument('--progressive_stage1_class_margin', default=0.5, type=float)
    subparsers.add_argument('--progressive_stage2_tii_margin', default=0.35, type=float)
    subparsers.add_argument('--progressive_stage2_adapter_margin', default=0.5, type=float)
    subparsers.add_argument('--progressive_stage2_class_margin', default=0.25, type=float)
    subparsers.add_argument('--progressive_excluded_logit_margin', default=20.0, type=float)
    subparsers.add_argument('--selective_rematching', action='store_true', help='evaluate only TII-selected top-k LoRAs and merge their task-local logits')
    subparsers.add_argument('--selective_candidate_tasks', default=3, type=int)
    subparsers.add_argument('--selective_tii_prior_weight', default=0.3, type=float)
    subparsers.add_argument('--selective_logit_temperature', default=1.0, type=float)
    subparsers.add_argument('--selective_adaptive', action='store_true', help='use fewer LoRAs when the TII task-score margin is confident')
    subparsers.add_argument('--selective_confident_margin', default=1.0, type=float)
    subparsers.add_argument('--selective_ambiguous_margin', default=0.35, type=float)
    subparsers.add_argument('--selective_candidate_source', default='tii', choices=['tii', 'cascade', 'router'], type=str)
    subparsers.add_argument('--selective_cascade_weight', default=0.5, type=float)
    subparsers.add_argument('--selective_excluded_logit_margin', default=20.0, type=float)
    subparsers.add_argument('--distilled_router_rematching', action='store_true', help='train a top-k task router from true task labels and exhaustive teacher scores on training images')
    subparsers.add_argument('--distilled_router_samples_per_class', default=8, type=int)
    subparsers.add_argument('--distilled_router_validation_ratio', default=0.25, type=float)
    subparsers.add_argument('--distilled_router_hidden_dim', default=256, type=int)
    subparsers.add_argument('--distilled_router_dropout', default=0.1, type=float)
    subparsers.add_argument('--distilled_router_lr', default=0.001, type=float)
    subparsers.add_argument('--distilled_router_weight_decay', default=0.01, type=float)
    subparsers.add_argument('--distilled_router_batch_size', default=256, type=int)
    subparsers.add_argument('--distilled_router_epochs', default=50, type=int)
    subparsers.add_argument('--distilled_router_patience', default=8, type=int)
    subparsers.add_argument('--distilled_router_teacher_weight', default=0.3, type=float)
    subparsers.add_argument('--distilled_router_temperature', default=1.0, type=float)
    subparsers.add_argument('--distilled_router_teacher_prior', default=0.3, type=float)
    subparsers.add_argument('--distilled_router_teacher_temperature', default=1.0, type=float)
    subparsers.add_argument('--distilled_router_min_validation_gain', default=0.0, type=float)
    subparsers.add_argument('--semantic_distill', action='store_true', help='use semantic-aware weighting for relation distillation')
    subparsers.add_argument('--semantic_backend', default='hash', choices=['hash', 'clip', 'auto'], type=str)
    subparsers.add_argument('--semantic_clip_model', default='ViT-B-16', type=str)
    subparsers.add_argument('--semantic_clip_pretrained', default='openai', type=str)
    subparsers.add_argument('--semantic_clip_templates', default='a photo of a {}.', type=str)
    subparsers.add_argument('--semantic_dim', default=512, type=int)
    subparsers.add_argument('--semantic_class_name_file', default='', type=str)
    subparsers.add_argument('--semantic_alpha', default=0.05, type=float)
    subparsers.add_argument('--semantic_floor', default=0.2, type=float)
    subparsers.add_argument('--semantic_sharpness', default=1.0, type=float)    # Misc parameters
    subparsers.add_argument('--semantic_top_k', default=5, type=int)
    subparsers.add_argument('--semantic_mode', default='adaptive_gate', choices=['adaptive_gate', 'topk_mix', 'weight'], type=str)
    subparsers.add_argument('--semantic_projection', action='store_true', help='use semantic projection to generate CRCT features from related classes')
    subparsers.add_argument('--semantic_projection_ratio', default=0.25, type=float)
    subparsers.add_argument('--semantic_projection_top_k', default=5, type=int)
    subparsers.add_argument('--semantic_projection_strength', default=1.0, type=float)
    subparsers.add_argument('--semantic_projection_mode', default='mean_shift', choices=['mean_shift', 'paper', 'covariance_transfer'], type=str)
    subparsers.add_argument('--semantic_projection_alpha', default=0.1, type=float)
    subparsers.add_argument('--semantic_cov_transfer_min_scale', default=0.5, type=float)
    subparsers.add_argument('--semantic_cov_transfer_max_scale', default=2.0, type=float)
    subparsers.add_argument('--semantic_projection_preserve_norm', action='store_true')
    subparsers.add_argument('--semantic_projection_filter', action='store_true', help='filter semantic projected CRCT features by target feature distribution')
    subparsers.add_argument('--semantic_projection_filter_multiplier', default=3, type=int)
    subparsers.add_argument('--semantic_projection_filter_cosine_weight', default=0.1, type=float)
    subparsers.add_argument('--semantic_feature_adapter', action='store_true', help='align semantic embeddings to HRM feature means before semantic projection')
    subparsers.add_argument('--semantic_adapter_dim', default=512, type=int)
    subparsers.add_argument('--semantic_adapter_ridge', default=0.01, type=float)
    subparsers.add_argument('--semantic_adapter_blend', default=1.0, type=float)
    subparsers.add_argument('--semantic_adapter_min_classes', default=5, type=int)
    subparsers.add_argument('--print_freq', type=int, default=10, help = 'The frequency of printing')
